apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openquestion.fullname" . }}
  labels:
    {{- include "openquestion.labels" . | nindent 4 }}
spec:
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
